### ISSUE TITLE
No estas usando la función de setUp()

### ISSUE THREAD

**Issue by evolentini** [charlieromano/CESE2020#1]
No es que sea obligatorio pero ademas de escribir mas codigo es mas fácil que en algunas de las funciones de prueba te equivoques y pierdas tiempo. 

https://github.com/charlieromano/CESE2020/blob/33d1f67eb403d38063508c6d82322b8c454c9354/leds/test/test_leds.c#L23-L24

**Comment by charlieromano** [comment]
Actualizado en el commit 74358a3.
