### ISSUE TITLE
Se debe definir una función para recuperar el estado de un led

### ISSUE THREAD

**Issue by evolentini** [charlieromano/CESE2020#3]
Esta prueba debe llamas a una función tipo `LedGetState()` o `LedIsON()` o `LedIsOFF()` y verificar que el resultado de esa función coincide con el estado del led.

https://github.com/charlieromano/CESE2020/blob/33d1f67eb403d38063508c6d82322b8c454c9354/leds/test/test_leds.c#L58-L63

**Comment by charlieromano** [comment]
Actualizado en el commit 74358a3.
