### ISSUE TITLE
No se aplico correctamente la metodología

### ISSUE THREAD

**Issue by evolentini** [charlieromano/CESE2020#5]
Esta definición no se utiliza en el código, por lo tanto no se escribió para pasar una prueba que es lo que plantea TDD.

https://github.com/charlieromano/CESE2020/blob/33d1f67eb403d38063508c6d82322b8c454c9354/leds/src/leds.c#L3

**Comment by charlieromano** [comment]
Actualizado en el commit 74358a3.
